spring:
 cloud:
   gateway:
     routes:
       - id: TxnService
         uri: lb://TXNSERVICE
         predicates:
           - Path=/txns/**
         filters:
           - AuthenticationFilter


       - id: UserService
         uri: lb://USERSERVICE
         predicates:
           - Path=/users/**
         filters:
           - AuthenticationFilter

       - id: WalletService
         uri: lb://WALLETSERVICE
         predicates:
           - Path=/wallets/**

 application:
   name: WALLETGATEWAY

discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/